### ISSUE TITLE
Is Cython compatible with pycuda?

### ISSUE THREAD

**Issue by kareemcarr** [kareemcarr/cs205_2017_project#2]
We need to determine if it's viable to mix Cython and pycuda in our project or whether we will need include a C/C++ component in our software.

**Comment by eifer4** [comment]
http://conference.scipy.org/static/wiki/seljebotn_cython.pdf --> mentions adding pycuda as an extension

Will run a test case. I imagine that we can always interface with the NVIDIA C code in CUDA directly if we have to from cython. Though, not sure if we really need cython other than for speed.

**Comment by eifer4** [comment]
I think we should close this since it doesn't look like we'll be using cython?
